/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./utils/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],

  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "rgb(var(--color-primary) / <alpha-value>)",
          0: "rgb(var(--color-primary-0) / <alpha-value>)",
          50: "rgb(var(--color-primary-50) / <alpha-value>)",
          100: "rgb(var(--color-primary-100) / <alpha-value>)",
          200: "rgb(var(--color-primary-200) / <alpha-value>)",
          300: "rgb(var(--color-primary-300) / <alpha-value>)",
          400: "rgb(var(--color-primary-400) / <alpha-value>)",
          500: "rgb(var(--color-primary-500) / <alpha-value>)",
          600: "rgb(var(--color-primary-600) / <alpha-value>)",
          700: "rgb(var(--color-primary-700) / <alpha-value>)",
          800: "rgb(var(--color-primary-800) / <alpha-value>)",
          900: "rgb(var(--color-primary-900) / <alpha-value>)",
          950: "rgb(var(--color-primary-950) / <alpha-value>)",
        },
        secondary: {
          DEFAULT: "rgb(var(--color-secondary) / <alpha-value>)",
          0: "rgb(var(--color-secondary-0) / <alpha-value>)",
          50: "rgb(var(--color-secondary-50) / <alpha-value>)",
          100: "rgb(var(--color-secondary-100) / <alpha-value>)",
          200: "rgb(var(--color-secondary-200) / <alpha-value>)",
          300: "rgb(var(--color-secondary-300) / <alpha-value>)",
          400: "rgb(var(--color-secondary-400) / <alpha-value>)",
          500: "rgb(var(--color-secondary-500) / <alpha-value>)",
          600: "rgb(var(--color-secondary-600) / <alpha-value>)",
          700: "rgb(var(--color-secondary-700) / <alpha-value>)",
          800: "rgb(var(--color-secondary-800) / <alpha-value>)",
          900: "rgb(var(--color-secondary-900) / <alpha-value>)",
          950: "rgb(var(--color-secondary-950) / <alpha-value>)",
        },
        tertiary: {
          DEFAULT: "rgb(var(--color-tertiary) / <alpha-value>)",
          0: "rgb(var(--color-tertiary-0) / <alpha-value>)",
          50: "rgb(var(--color-tertiary-50) / <alpha-value>)",
          100: "rgb(var(--color-tertiary-100) / <alpha-value>)",
          200: "rgb(var(--color-tertiary-200) / <alpha-value>)",
          300: "rgb(var(--color-tertiary-300) / <alpha-value>)",
          400: "rgb(var(--color-tertiary-400) / <alpha-value>)",
          500: "rgb(var(--color-tertiary-500) / <alpha-value>)",
          600: "rgb(var(--color-tertiary-600) / <alpha-value>)",
          700: "rgb(var(--color-tertiary-700) / <alpha-value>)",
          800: "rgb(var(--color-tertiary-800) / <alpha-value>)",
          900: "rgb(var(--color-tertiary-900) / <alpha-value>)",
          950: "rgb(var(--color-tertiary-950) / <alpha-value>)",
        },
        error: {
          DEFAULT: "rgb(var(--color-error) / <alpha-value>)",
          0: "rgb(var(--color-error-0) / <alpha-value>)",
          50: "rgb(var(--color-error-50) / <alpha-value>)",
          100: "rgb(var(--color-error-100) / <alpha-value>)",
          200: "rgb(var(--color-error-200) / <alpha-value>)",
          300: "rgb(var(--color-error-300) / <alpha-value>)",
          400: "rgb(var(--color-error-400) / <alpha-value>)",
          500: "rgb(var(--color-error-500) / <alpha-value>)",
          600: "rgb(var(--color-error-600) / <alpha-value>)",
          700: "rgb(var(--color-error-700) / <alpha-value>)",
          800: "rgb(var(--color-error-800) / <alpha-value>)",
          900: "rgb(var(--color-error-900) / <alpha-value>)",
          950: "rgb(var(--color-error-950) / <alpha-value>)",
        },
        success: {
          DEFAULT: "rgb(var(--color-success) / <alpha-value>)",
          0: "rgb(var(--color-success-0) / <alpha-value>)",
          50: "rgb(var(--color-success-50) / <alpha-value>)",
          100: "rgb(var(--color-success-100) / <alpha-value>)",
          200: "rgb(var(--color-success-200) / <alpha-value>)",
          300: "rgb(var(--color-success-300) / <alpha-value>)",
          400: "rgb(var(--color-success-400) / <alpha-value>)",
          500: "rgb(var(--color-success-500) / <alpha-value>)",
          600: "rgb(var(--color-success-600) / <alpha-value>)",
          700: "rgb(var(--color-success-700) / <alpha-value>)",
          800: "rgb(var(--color-success-800) / <alpha-value>)",
          900: "rgb(var(--color-success-900) / <alpha-value>)",
          950: "rgb(var(--color-success-950) / <alpha-value>)",
        },
        warning: {
          DEFAULT: "rgb(var(--color-warning) / <alpha-value>)",
          0: "rgb(var(--color-warning-0) / <alpha-value>)",
          50: "rgb(var(--color-warning-50) / <alpha-value>)",
          100: "rgb(var(--color-warning-100) / <alpha-value>)",
          200: "rgb(var(--color-warning-200) / <alpha-value>)",
          300: "rgb(var(--color-warning-300) / <alpha-value>)",
          400: "rgb(var(--color-warning-400) / <alpha-value>)",
          500: "rgb(var(--color-warning-500) / <alpha-value>)",
          600: "rgb(var(--color-warning-600) / <alpha-value>)",
          700: "rgb(var(--color-warning-700) / <alpha-value>)",
          800: "rgb(var(--color-warning-800) / <alpha-value>)",
          900: "rgb(var(--color-warning-900) / <alpha-value>)",
          950: "rgb(var(--color-warning-950) / <alpha-value>)",
        },
        info: {
          DEFAULT: "rgb(var(--color-info) / <alpha-value>)",
          0: "rgb(var(--color-info-0) / <alpha-value>)",
          50: "rgb(var(--color-info-50) / <alpha-value>)",
          100: "rgb(var(--color-info-100) / <alpha-value>)",
          200: "rgb(var(--color-info-200) / <alpha-value>)",
          300: "rgb(var(--color-info-300) / <alpha-value>)",
          400: "rgb(var(--color-info-400) / <alpha-value>)",
          500: "rgb(var(--color-info-500) / <alpha-value>)",
          600: "rgb(var(--color-info-600) / <alpha-value>)",
          700: "rgb(var(--color-info-700) / <alpha-value>)",
          800: "rgb(var(--color-info-800) / <alpha-value>)",
          900: "rgb(var(--color-info-900) / <alpha-value>)",
          950: "rgb(var(--color-info-950) / <alpha-value>)",
        },
        typography: {
          DEFAULT: "rgb(var(--color-typography) / <alpha-value>)",
          0: "rgb(var(--color-typography-0) / <alpha-value>)",
          50: "rgb(var(--color-typography-50) / <alpha-value>)",
          100: "rgb(var(--color-typography-100) / <alpha-value>)",
          200: "rgb(var(--color-typography-200) / <alpha-value>)",
          300: "rgb(var(--color-typography-300) / <alpha-value>)",
          400: "rgb(var(--color-typography-400) / <alpha-value>)",
          500: "rgb(var(--color-typography-500) / <alpha-value>)",
          600: "rgb(var(--color-typography-600) / <alpha-value>)",
          700: "rgb(var(--color-typography-700) / <alpha-value>)",
          800: "rgb(var(--color-typography-800) / <alpha-value>)",
          900: "rgb(var(--color-typography-900) / <alpha-value>)",
          950: "rgb(var(--color-typography-950) / <alpha-value>)",
        },
        background: {
          DEFAULT: "rgb(var(--color-background) / <alpha-value>)",
          0: "rgb(var(--color-background-0) / <alpha-value>)",
          50: "rgb(var(--color-background-50) / <alpha-value>)",
          100: "rgb(var(--color-background-100) / <alpha-value>)",
          200: "rgb(var(--color-background-200) / <alpha-value>)",
          300: "rgb(var(--color-background-300) / <alpha-value>)",
          400: "rgb(var(--color-background-400) / <alpha-value>)",
          500: "rgb(var(--color-background-500) / <alpha-value>)",
          600: "rgb(var(--color-background-600) / <alpha-value>)",
          700: "rgb(var(--color-background-700) / <alpha-value>)",
          800: "rgb(var(--color-background-800) / <alpha-value>)",
          900: "rgb(var(--color-background-900) / <alpha-value>)",
          950: "rgb(var(--color-background-950) / <alpha-value>)",
          error: "rgb(var(--color-background-error) / <alpha-value>)",
          warning: "rgb(var(--color-background-warning) / <alpha-value>)",
          success: "rgb(var(--color-background-success) / <alpha-value>)",
          muted: "rgb(var(--color-background-muted) / <alpha-value>)",
          info: "rgb(var(--color-background-info) / <alpha-value>)",
        },
        indicator: {
          primary: "rgb(var(--color-indicator-primary) / <alpha-value>)",
          info: "rgb(var(--color-indicator-info) / <alpha-value>)",
          error: "rgb(var(--color-indicator-error) / <alpha-value>)",
        },
      },
      fontFamily: {
        sans: ["Sora-Regular", "sans-serif"],
        sora: ["Sora-Regular", "sans-serif"],
        "sora-thin": ["Sora-Thin", "sans-serif"],
        "sora-extralight": ["Sora-ExtraLight", "sans-serif"],
        "sora-light": ["Sora-Light", "sans-serif"],
        "sora-medium": ["Sora-Medium", "sans-serif"],
        "sora-semibold": ["Sora-SemiBold", "sans-serif"],
        "sora-bold": ["Sora-Bold", "sans-serif"],
        "sora-extrabold": ["Sora-ExtraBold", "sans-serif"],
        heading: ["Sora-Bold", "sans-serif"],
        body: ["Sora-Regular", "sans-serif"],
      },
    },
  },
};
